//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Ticket_Reservation_.Models.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public string cid { get; set; }
        public string ticketid { get; set; }
        public string fromaddress { get; set; }
        public string toaddress { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    }
}
