//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Ticket_Reservation_.Models.BusinessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusTicketReservationSystemEntities : DbContext
    {
        public BusTicketReservationSystemEntities()
            : base("name=BusTicketReservationSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<bus> buses { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<history> histories { get; set; }
        public virtual DbSet<place> places { get; set; }
        public virtual DbSet<route> routes { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<seatAvailability> seatAvailabilities { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
    }
}
